version: '3'


services:
  db:
    image: postgres:latest
    env_file:
      - environments/db.env
    volumes:
      - django_db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d django_db" ]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  celery_worker:
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file:
      - environments/web.env
    command: celery -A web worker --loglevel=info
    volumes:
      - .:/code
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f 'celery worker' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    working_dir: /code/web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file:
      - environments/web.env
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/code
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 1s
      timeout: 2s
      retries: 3
    depends_on:
      web:
        condition: service_healthy

volumes:
  django_db_volume:
  redis: